"""Regenerate registry/algorithms.yaml from the YAML frontmatter of each card.

Usage:  python scripts/build_registry.py
"""
from __future__ import annotations

import pathlib
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required: pip install pyyaml")

ROOT = pathlib.Path(__file__).resolve().parent.parent
ALGO_DIR = ROOT / "docs" / "algorithms"
OUT = ROOT / "registry" / "algorithms.yaml"

FIELDS = ["id", "name", "family", "regime", "penalty", "output", "status", "refs"]


def parse_frontmatter(text: str) -> dict | None:
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    return yaml.safe_load(text[3:end])


def main() -> int:
    cards = []
    for md in sorted(ALGO_DIR.glob("*.md")):
        if md.name == "index.md":
            continue
        fm = parse_frontmatter(md.read_text(encoding="utf-8"))
        if not fm:
            print(f"WARN: no frontmatter in {md.name}")
            continue
        cards.append({k: fm.get(k) for k in FIELDS})
    OUT.write_text(
        "# Auto-generated by scripts/build_registry.py. Do not edit by hand.\n"
        + yaml.safe_dump({"version": 1, "algorithms": cards}, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    print(f"Wrote {len(cards)} cards to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
