"""Build notebooks/phase2_multidata.ipynb programmatically."""
import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def code_cell(source):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source,
    }


def md_cell(source):
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source,
    }


cells = []

# ─────────────────────────────────────────────────────────────────────────────
# Section 0 – Setup & Imports
# ─────────────────────────────────────────────────────────────────────────────
cells.append(md_cell(
    "# Phase 2 – Multi-Dataset GLM Algorithm Arena\n\n"
    "Comprehensive comparison of **all solvers** across **20 real datasets** "
    "with per-dataset **t-SNE + UMAP** embeddings of the solution manifold."
))

cells.append(code_cell(
    "import os, sys, warnings\n"
    "warnings.filterwarnings('ignore')\n"
    "sys.path.insert(0, os.path.abspath('..'))\n"
    "\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.patches as mpatches\n"
    "from matplotlib.lines import Line2D\n"
    "from sklearn.preprocessing import StandardScaler\n"
    "from sklearn.datasets import load_diabetes, fetch_california_housing, load_breast_cancer\n"
    "from sklearn.datasets import fetch_openml\n"
    "from sklearn.manifold import TSNE, MDS\n"
    "import umap\n"
    "\n"
    "from src.glmzoo.solvers.classical.ols      import OLSSolver\n"
    "from src.glmzoo.solvers.classical.ridge    import RidgeSolver\n"
    "from src.glmzoo.solvers.classical.glm_irls import GLMIRLSSolver\n"
    "from src.glmzoo.solvers.penalized.lasso_cd       import LassoCDSolver\n"
    "from src.glmzoo.solvers.penalized.elastic_net    import ElasticNetSolver\n"
    "from src.glmzoo.solvers.penalized.adaptive_lasso import AdaptiveLassoSolver\n"
    "from src.glmzoo.solvers.penalized.scad_lla       import SCADLLASolver\n"
    "from src.glmzoo.solvers.penalized.mcp_cd         import MCPCDSolver\n"
    "from src.glmzoo.solvers.penalized.group_lasso    import GroupLassoSolver\n"
    "from src.glmzoo.solvers.penalized.fused_lasso    import FusedLassoSolver\n"
    "from src.glmzoo.solvers.path.lars          import LARSSolver\n"
    "from src.glmzoo.solvers.first_order.ista   import ISTASolver\n"
    "from src.glmzoo.solvers.first_order.fista  import FISTASolver\n"
    "from src.glmzoo.solvers.online.sgd                 import SGDSolver\n"
    "from src.glmzoo.solvers.online.implicit_sgd        import ImplicitSGDSolver\n"
    "from src.glmzoo.solvers.online.adagrad             import AdaGradSolver\n"
    "from src.glmzoo.solvers.online.fobos               import FOBOSSolver\n"
    "from src.glmzoo.solvers.online.rda                 import RDASolver\n"
    "from src.glmzoo.solvers.online.truncated_gradient  import TruncatedGradientSolver\n"
    "from src.glmzoo.solvers.online.renewable_glm       import RenewableGLMSolver\n"
    "\n"
    "print('All imports OK')\n"
))

# ─────────────────────────────────────────────────────────────────────────────
# Section 1 – Load 20 Real Datasets
# ─────────────────────────────────────────────────────────────────────────────
cells.append(md_cell("## Section 1 – Load 20 Real Datasets"))

cells.append(code_cell(
    "def prep_regression(X_arr, y_arr, n_max=3000):\n"
    "    if len(y_arr) > n_max:\n"
    "        rng = np.random.default_rng(0)\n"
    "        idx = rng.choice(len(y_arr), n_max, replace=False)\n"
    "        X_arr, y_arr = X_arr[idx], y_arr[idx]\n"
    "    X_arr = StandardScaler().fit_transform(X_arr)\n"
    "    y_arr = (y_arr - y_arr.mean()) / (y_arr.std() + 1e-12)\n"
    "    return X_arr, y_arr\n"
    "\n"
    "def prep_logistic(X_arr, y_arr, n_max=3000):\n"
    "    if len(y_arr) > n_max:\n"
    "        rng = np.random.default_rng(0)\n"
    "        idx = rng.choice(len(y_arr), n_max, replace=False)\n"
    "        X_arr, y_arr = X_arr[idx], y_arr[idx]\n"
    "    X_arr = StandardScaler().fit_transform(X_arr)\n"
    "    uniq = np.unique(y_arr[np.isfinite(y_arr)])\n"
    "    if len(uniq) == 2:\n"
    "        y_arr = (y_arr == uniq[1]).astype(float)\n"
    "    else:\n"
    "        y_arr = (y_arr > np.median(y_arr)).astype(float)\n"
    "    return X_arr, y_arr\n"
    "\n"
    "datasets = {}\n"
    "print('Helper functions defined')\n"
))

# Dataset loading cells – split into groups to keep cells manageable
cells.append(code_cell(
    "# ── 1. Diabetes ────────────────────────────────────────────────────────\n"
    "try:\n"
    "    bunch = load_diabetes()\n"
    "    X_a, y_a = prep_regression(bunch.data, bunch.target.astype(float))\n"
    "    datasets['Diabetes'] = dict(X=X_a, y=y_a, link='identity', kind='regression')\n"
    "    print(f'Diabetes: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Diabetes: {e}')\n"
    "\n"
    "# ── 2. CA Housing ──────────────────────────────────────────────────────\n"
    "try:\n"
    "    bunch = fetch_california_housing()\n"
    "    X_a, y_a = prep_regression(bunch.data, bunch.target.astype(float), n_max=2000)\n"
    "    datasets['CA Housing'] = dict(X=X_a, y=y_a, link='identity', kind='regression')\n"
    "    print(f'CA Housing: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: CA Housing: {e}')\n"
    "\n"
    "# ── 3. Concrete Strength (openml 4353) ─────────────────────────────────\n"
    "try:\n"
    "    bunch = fetch_openml(data_id=4353, as_frame=True, parser='auto')\n"
    "    X_df = bunch.data.select_dtypes(include=[np.number]).dropna()\n"
    "    y_s  = pd.to_numeric(bunch.target, errors='coerce')\n"
    "    idx  = X_df.index.intersection(y_s.dropna().index)\n"
    "    X_a, y_a = prep_regression(X_df.loc[idx].values.astype(float), y_s.loc[idx].values.astype(float))\n"
    "    datasets['Concrete Strength'] = dict(X=X_a, y=y_a, link='identity', kind='regression')\n"
    "    print(f'Concrete Strength: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Concrete Strength: {e}')\n"
    "\n"
    "# ── 4. Energy Efficiency (openml 242) ──────────────────────────────────\n"
    "try:\n"
    "    bunch = fetch_openml(data_id=242, as_frame=True, parser='auto')\n"
    "    X_df = bunch.data.select_dtypes(include=[np.number]).dropna()\n"
    "    y_s  = pd.to_numeric(bunch.target, errors='coerce')\n"
    "    idx  = X_df.index.intersection(y_s.dropna().index)\n"
    "    X_a, y_a = prep_regression(X_df.loc[idx].values.astype(float), y_s.loc[idx].values.astype(float))\n"
    "    datasets['Energy Efficiency'] = dict(X=X_a, y=y_a, link='identity', kind='regression')\n"
    "    print(f'Energy Efficiency: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Energy Efficiency: {e}')\n"
    "\n"
    "# ── 5. Abalone (openml 183) ────────────────────────────────────────────\n"
    "try:\n"
    "    bunch = fetch_openml(data_id=183, as_frame=True, parser='auto')\n"
    "    X_df = bunch.data.select_dtypes(include=[np.number]).dropna()\n"
    "    y_s  = pd.to_numeric(bunch.target, errors='coerce')\n"
    "    idx  = X_df.index.intersection(y_s.dropna().index)\n"
    "    X_a, y_a = prep_regression(X_df.loc[idx].values.astype(float), y_s.loc[idx].values.astype(float), n_max=2000)\n"
    "    datasets['Abalone'] = dict(X=X_a, y=y_a, link='identity', kind='regression')\n"
    "    print(f'Abalone: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Abalone: {e}')\n"
))

cells.append(code_cell(
    "# ── 6. Wine Quality Red (openml 40691) ─────────────────────────────────\n"
    "try:\n"
    "    bunch = fetch_openml(data_id=40691, as_frame=True, parser='auto')\n"
    "    X_df = bunch.data.select_dtypes(include=[np.number]).dropna()\n"
    "    y_s  = pd.to_numeric(bunch.target, errors='coerce')\n"
    "    idx  = X_df.index.intersection(y_s.dropna().index)\n"
    "    X_a, y_a = prep_regression(X_df.loc[idx].values.astype(float), y_s.loc[idx].values.astype(float))\n"
    "    datasets['Wine Quality Red'] = dict(X=X_a, y=y_a, link='identity', kind='regression')\n"
    "    print(f'Wine Quality Red: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Wine Quality Red: {e}')\n"
    "\n"
    "# ── 7. Airfoil Noise (openml 41519) ────────────────────────────────────\n"
    "try:\n"
    "    bunch = fetch_openml(data_id=41519, as_frame=True, parser='auto')\n"
    "    X_df = bunch.data.select_dtypes(include=[np.number]).dropna()\n"
    "    y_s  = pd.to_numeric(bunch.target, errors='coerce')\n"
    "    idx  = X_df.index.intersection(y_s.dropna().index)\n"
    "    X_a, y_a = prep_regression(X_df.loc[idx].values.astype(float), y_s.loc[idx].values.astype(float))\n"
    "    datasets['Airfoil Noise'] = dict(X=X_a, y=y_a, link='identity', kind='regression')\n"
    "    print(f'Airfoil Noise: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Airfoil Noise: {e}')\n"
    "\n"
    "# ── 8. Auto MPG (openml 196) ────────────────────────────────────────────\n"
    "try:\n"
    "    bunch = fetch_openml(data_id=196, as_frame=True, parser='auto')\n"
    "    X_df = bunch.data.select_dtypes(include=[np.number]).dropna()\n"
    "    y_s  = pd.to_numeric(bunch.target, errors='coerce')\n"
    "    idx  = X_df.index.intersection(y_s.dropna().index)\n"
    "    X_a, y_a = prep_regression(X_df.loc[idx].values.astype(float), y_s.loc[idx].values.astype(float))\n"
    "    datasets['Auto MPG'] = dict(X=X_a, y=y_a, link='identity', kind='regression')\n"
    "    print(f'Auto MPG: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Auto MPG: {e}')\n"
    "\n"
    "# ── 9. Servo (openml 275) ───────────────────────────────────────────────\n"
    "try:\n"
    "    bunch = fetch_openml(data_id=275, as_frame=True, parser='auto')\n"
    "    X_df = bunch.data.select_dtypes(include=[np.number]).dropna()\n"
    "    y_s  = pd.to_numeric(bunch.target, errors='coerce')\n"
    "    idx  = X_df.index.intersection(y_s.dropna().index)\n"
    "    if len(idx) < 5:\n"
    "        raise ValueError('Too few numeric features')\n"
    "    X_a, y_a = prep_regression(X_df.loc[idx].values.astype(float), y_s.loc[idx].values.astype(float))\n"
    "    datasets['Servo'] = dict(X=X_a, y=y_a, link='identity', kind='regression')\n"
    "    print(f'Servo: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Servo: {e}')\n"
    "\n"
    "# ── 10. Communities & Crime (openml 315) ───────────────────────────────\n"
    "try:\n"
    "    bunch = fetch_openml(data_id=315, as_frame=True, parser='auto')\n"
    "    num_cols = bunch.data.select_dtypes(include=[np.number]).columns.tolist()\n"
    "    y_s = pd.to_numeric(bunch.target, errors='coerce')\n"
    "    X_df = bunch.data[num_cols[:20]].copy()\n"
    "    X_df = X_df.replace([np.inf, -np.inf], np.nan).dropna()\n"
    "    idx  = X_df.index.intersection(y_s.dropna().index)\n"
    "    X_a, y_a = prep_regression(X_df.loc[idx].values.astype(float), y_s.loc[idx].values.astype(float), n_max=1000)\n"
    "    datasets['Communities Crime'] = dict(X=X_a, y=y_a, link='identity', kind='regression')\n"
    "    print(f'Communities Crime: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Communities Crime: {e}')\n"
))

cells.append(code_cell(
    "# ── 11. Bike Sharing (openml 42712) ────────────────────────────────────\n"
    "try:\n"
    "    bunch = fetch_openml(data_id=42712, as_frame=True, parser='auto')\n"
    "    X_df = bunch.data.select_dtypes(include=[np.number]).dropna()\n"
    "    y_s  = pd.to_numeric(bunch.target, errors='coerce')\n"
    "    idx  = X_df.index.intersection(y_s.dropna().index)\n"
    "    X_a, y_a = prep_regression(X_df.loc[idx].values.astype(float), y_s.loc[idx].values.astype(float), n_max=2000)\n"
    "    datasets['Bike Sharing'] = dict(X=X_a, y=y_a, link='identity', kind='regression')\n"
    "    print(f'Bike Sharing: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Bike Sharing: {e}')\n"
    "\n"
    "# ── 12. Student Performance (openml 43) ────────────────────────────────\n"
    "try:\n"
    "    bunch = fetch_openml(data_id=43, as_frame=True, parser='auto')\n"
    "    X_df = bunch.data.select_dtypes(include=[np.number]).dropna()\n"
    "    y_s  = pd.to_numeric(bunch.target, errors='coerce')\n"
    "    idx  = X_df.index.intersection(y_s.dropna().index)\n"
    "    if len(idx) < 5 or X_df.loc[idx].shape[1] < 1:\n"
    "        raise ValueError('Too few usable numeric columns')\n"
    "    X_a, y_a = prep_regression(X_df.loc[idx].values.astype(float), y_s.loc[idx].values.astype(float))\n"
    "    datasets['Student Performance'] = dict(X=X_a, y=y_a, link='identity', kind='regression')\n"
    "    print(f'Student Performance: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Student Performance: {e}')\n"
    "\n"
    "# ── 13. Breast Cancer (sklearn) ─────────────────────────────────────────\n"
    "try:\n"
    "    bunch = load_breast_cancer()\n"
    "    X_a, y_a = prep_logistic(bunch.data.astype(float), bunch.target.astype(float))\n"
    "    datasets['Breast Cancer'] = dict(X=X_a, y=y_a, link='logit', kind='logistic')\n"
    "    print(f'Breast Cancer: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Breast Cancer: {e}')\n"
    "\n"
    "# ── 14. Heart Disease (openml 53) ───────────────────────────────────────\n"
    "try:\n"
    "    bunch = fetch_openml(data_id=53, as_frame=True, parser='auto')\n"
    "    X_df = bunch.data.select_dtypes(include=[np.number]).dropna()\n"
    "    y_s  = pd.to_numeric(bunch.target, errors='coerce')\n"
    "    idx  = X_df.index.intersection(y_s.dropna().index)\n"
    "    y_raw = y_s.loc[idx].values.astype(float)\n"
    "    y_bin = (y_raw > 0).astype(float)\n"
    "    X_a, y_a = prep_logistic(X_df.loc[idx].values.astype(float), y_bin)\n"
    "    datasets['Heart Disease'] = dict(X=X_a, y=y_a, link='logit', kind='logistic')\n"
    "    print(f'Heart Disease: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Heart Disease: {e}')\n"
))

cells.append(code_cell(
    "# ── 15. Pima Diabetes (openml 37) ──────────────────────────────────────\n"
    "try:\n"
    "    bunch = fetch_openml(data_id=37, as_frame=True, parser='auto')\n"
    "    X_df = bunch.data.select_dtypes(include=[np.number]).dropna()\n"
    "    y_raw = bunch.target\n"
    "    # Map string labels if present\n"
    "    label_map = {'tested_positive': 1, 'tested_negative': 0, '1': 1, '0': 0,\n"
    "                 'pos': 1, 'neg': 0, 'yes': 1, 'no': 0}\n"
    "    y_s = y_raw.map(lambda v: label_map.get(str(v).lower(), np.nan))\n"
    "    y_s = pd.to_numeric(y_s, errors='coerce')\n"
    "    if y_s.isna().all():\n"
    "        y_s = pd.to_numeric(y_raw, errors='coerce')\n"
    "    idx  = X_df.index.intersection(y_s.dropna().index)\n"
    "    X_a, y_a = prep_logistic(X_df.loc[idx].values.astype(float), y_s.loc[idx].values.astype(float))\n"
    "    datasets['Pima Diabetes'] = dict(X=X_a, y=y_a, link='logit', kind='logistic')\n"
    "    print(f'Pima Diabetes: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Pima Diabetes: {e}')\n"
    "\n"
    "# ── 16. Ionosphere (openml 59) ──────────────────────────────────────────\n"
    "try:\n"
    "    bunch = fetch_openml(data_id=59, as_frame=True, parser='auto')\n"
    "    X_df = bunch.data.select_dtypes(include=[np.number])\n"
    "    X_df = X_df.loc[:, X_df.std() > 1e-6].dropna()\n"
    "    y_raw = bunch.target\n"
    "    y_map = {'g': 1, 'b': 0, 'good': 1, 'bad': 0, '1': 1, '0': 0}\n"
    "    y_s = y_raw.map(lambda v: y_map.get(str(v).lower(), np.nan))\n"
    "    y_s = pd.to_numeric(y_s, errors='coerce')\n"
    "    idx  = X_df.index.intersection(y_s.dropna().index)\n"
    "    X_a, y_a = prep_logistic(X_df.loc[idx].values.astype(float), y_s.loc[idx].values.astype(float))\n"
    "    datasets['Ionosphere'] = dict(X=X_a, y=y_a, link='logit', kind='logistic')\n"
    "    print(f'Ionosphere: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Ionosphere: {e}')\n"
    "\n"
    "# ── 17. Banknote Authentication (openml 1462) ───────────────────────────\n"
    "try:\n"
    "    bunch = fetch_openml(data_id=1462, as_frame=True, parser='auto')\n"
    "    X_df = bunch.data.select_dtypes(include=[np.number]).dropna()\n"
    "    y_s  = pd.to_numeric(bunch.target, errors='coerce')\n"
    "    if y_s.isna().all():\n"
    "        y_map2 = {'1': 1, '0': 0, 'yes': 1, 'no': 0}\n"
    "        y_s = bunch.target.map(lambda v: y_map2.get(str(v).lower(), np.nan))\n"
    "        y_s = pd.to_numeric(y_s, errors='coerce')\n"
    "    idx  = X_df.index.intersection(y_s.dropna().index)\n"
    "    X_a, y_a = prep_logistic(X_df.loc[idx].values.astype(float), y_s.loc[idx].values.astype(float))\n"
    "    datasets['Banknote Auth'] = dict(X=X_a, y=y_a, link='logit', kind='logistic')\n"
    "    print(f'Banknote Auth: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Banknote Auth: {e}')\n"
))

cells.append(code_cell(
    "# ── 18. Credit Approval (openml 29) ────────────────────────────────────\n"
    "try:\n"
    "    bunch = fetch_openml(data_id=29, as_frame=True, parser='auto')\n"
    "    X_df = bunch.data.select_dtypes(include=[np.number]).dropna()\n"
    "    y_raw = bunch.target\n"
    "    y_map = {'+': 1, '-': 0, '1': 1, '0': 0, '2': 1, 'yes': 1, 'no': 0}\n"
    "    y_s = y_raw.map(lambda v: y_map.get(str(v).strip().lower(), np.nan))\n"
    "    y_s = pd.to_numeric(y_s, errors='coerce')\n"
    "    idx  = X_df.index.intersection(y_s.dropna().index)\n"
    "    y_bin = y_s.loc[idx].values.astype(float)\n"
    "    if len(np.unique(y_bin)) < 2:\n"
    "        raise ValueError('Only one class')\n"
    "    X_a, y_a = prep_logistic(X_df.loc[idx].values.astype(float), y_bin)\n"
    "    datasets['Credit Approval'] = dict(X=X_a, y=y_a, link='logit', kind='logistic')\n"
    "    print(f'Credit Approval: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Credit Approval: {e}')\n"
    "\n"
    "# ── 19. Haberman Survival ───────────────────────────────────────────────\n"
    "try:\n"
    "    bunch = fetch_openml(name='haberman', version=1, as_frame=True, parser='auto')\n"
    "    X_df = bunch.data.select_dtypes(include=[np.number]).dropna()\n"
    "    y_raw = bunch.target\n"
    "    y_s = pd.to_numeric(y_raw, errors='coerce')\n"
    "    if y_s.isna().all():\n"
    "        surv_map = {'1': 0, '2': 1, 'yes': 0, 'no': 1, 'survived': 0, 'died': 1}\n"
    "        y_s = y_raw.map(lambda v: surv_map.get(str(v).lower(), np.nan))\n"
    "        y_s = pd.to_numeric(y_s, errors='coerce')\n"
    "    idx  = X_df.index.intersection(y_s.dropna().index)\n"
    "    y_bin = y_s.loc[idx].values.astype(float)\n"
    "    uniq = np.unique(y_bin[np.isfinite(y_bin)])\n"
    "    if len(uniq) > 2:\n"
    "        y_bin = (y_bin > np.median(y_bin)).astype(float)\n"
    "    elif len(uniq) == 2:\n"
    "        y_bin = (y_bin == uniq[1]).astype(float)\n"
    "    X_a, y_a = prep_logistic(X_df.loc[idx].values.astype(float), y_bin)\n"
    "    datasets['Haberman'] = dict(X=X_a, y=y_a, link='logit', kind='logistic')\n"
    "    print(f'Haberman: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Haberman: {e}')\n"
    "\n"
    "# ── 20. Spambase (openml 44) ────────────────────────────────────────────\n"
    "try:\n"
    "    bunch = fetch_openml(data_id=44, as_frame=True, parser='auto')\n"
    "    X_df = bunch.data.select_dtypes(include=[np.number]).dropna()\n"
    "    y_raw = bunch.target\n"
    "    y_s = pd.to_numeric(y_raw, errors='coerce')\n"
    "    if y_s.isna().any():\n"
    "        y_map3 = {'1': 1, '0': 0, 'spam': 1, 'nospam': 0, 'yes': 1, 'no': 0}\n"
    "        y_s = y_raw.map(lambda v: y_map3.get(str(v).lower(), np.nan))\n"
    "        y_s = pd.to_numeric(y_s, errors='coerce')\n"
    "    idx  = X_df.index.intersection(y_s.dropna().index)\n"
    "    X_a, y_a = prep_logistic(X_df.loc[idx].values.astype(float), y_s.loc[idx].values.astype(float), n_max=2000)\n"
    "    datasets['Spambase'] = dict(X=X_a, y=y_a, link='logit', kind='logistic')\n"
    "    print(f'Spambase: n={X_a.shape[0]}, p={X_a.shape[1]}')\n"
    "except Exception as e:\n"
    "    print(f'WARNING: Spambase: {e}')\n"
    "\n"
    "print(f'\\nLoaded {len(datasets)} datasets:')\n"
    "for name, ds in datasets.items():\n"
    "    print(f'  {name}: n={ds[\"X\"].shape[0]}, p={ds[\"X\"].shape[1]}, {ds[\"kind\"]}')\n"
))

# ─────────────────────────────────────────────────────────────────────────────
# Section 2 – Solver Grid
# ─────────────────────────────────────────────────────────────────────────────
cells.append(md_cell("## Section 2 – Comprehensive Solver Hyperparameter Grid"))

cells.append(code_cell(
    "# Each entry: (SolverClass, config_dict, short_label)\n"
    "SOLVER_CONFIGS = []\n"
    "\n"
    "# ── Classical ───────────────────────────────────────────────────────────\n"
    "SOLVER_CONFIGS += [\n"
    "    (OLSSolver,     {}, 'OLS'),\n"
    "    (GLMIRLSSolver, {}, 'IRLS'),\n"
    "    (LARSSolver,    {}, 'LARS'),\n"
    "]\n"
    "\n"
    "# ── Ridge ────────────────────────────────────────────────────────────────\n"
    "for lam in [0.001, 0.01, 0.1, 1.0, 5.0, 10.0, 50.0, 100.0]:\n"
    "    SOLVER_CONFIGS.append((RidgeSolver, {'lam': lam}, f'Ridge(\u03bb={lam})'))\n"
    "\n"
    "# ── Lasso CD ─────────────────────────────────────────────────────────────\n"
    "for lam in [0.001, 0.005, 0.01, 0.05, 0.1, 0.2, 0.5, 1.0]:\n"
    "    SOLVER_CONFIGS.append((LassoCDSolver, {'lam': lam}, f'LassoCD(\u03bb={lam})'))\n"
    "\n"
    "# ── ElasticNet ───────────────────────────────────────────────────────────\n"
    "for lam in [0.01, 0.05, 0.1, 0.5]:\n"
    "    for alpha in [0.1, 0.3, 0.5, 0.7, 0.9]:\n"
    "        SOLVER_CONFIGS.append((ElasticNetSolver, {'lam': lam, 'alpha': alpha},\n"
    "                               f'EN(\u03bb={lam},\u03b1={alpha})'))\n"
    "\n"
    "# ── ISTA / FISTA ─────────────────────────────────────────────────────────\n"
    "for lam in [0.001, 0.005, 0.01, 0.05, 0.1, 0.3, 0.5, 1.0]:\n"
    "    SOLVER_CONFIGS.append((ISTASolver,  {'lam': lam}, f'ISTA(\u03bb={lam})'))\n"
    "    SOLVER_CONFIGS.append((FISTASolver, {'lam': lam}, f'FISTA(\u03bb={lam})'))\n"
    "\n"
    "# ── Adaptive Lasso ───────────────────────────────────────────────────────\n"
    "for lam in [0.005, 0.01, 0.05, 0.1, 0.5, 1.0]:\n"
    "    SOLVER_CONFIGS.append((AdaptiveLassoSolver, {'lam': lam}, f'AdaLasso(\u03bb={lam})'))\n"
    "\n"
    "# ── SCAD ─────────────────────────────────────────────────────────────────\n"
    "for lam in [0.01, 0.05, 0.1, 0.3, 0.5, 1.0]:\n"
    "    SOLVER_CONFIGS.append((SCADLLASolver, {'lam': lam}, f'SCAD(\u03bb={lam})'))\n"
    "\n"
    "# ── MCP ──────────────────────────────────────────────────────────────────\n"
    "for lam in [0.01, 0.05, 0.1, 0.3, 0.5, 1.0]:\n"
    "    SOLVER_CONFIGS.append((MCPCDSolver, {'lam': lam}, f'MCP(\u03bb={lam})'))\n"
    "\n"
    "# ── Group Lasso (groups injected at run time from p) ─────────────────────\n"
    "for lam in [0.01, 0.05, 0.1, 0.5, 1.0]:\n"
    "    SOLVER_CONFIGS.append((GroupLassoSolver, {'lam': lam}, f'GroupLasso(\u03bb={lam})'))\n"
    "\n"
    "# ── Fused Lasso (regression only) ────────────────────────────────────────\n"
    "for lam1 in [0.01, 0.05, 0.1]:\n"
    "    for lam2 in [0.01, 0.05, 0.1]:\n"
    "        SOLVER_CONFIGS.append((FusedLassoSolver, {'lam1': lam1, 'lam2': lam2},\n"
    "                               f'Fused(\u03bb1={lam1},\u03bb2={lam2})'))\n"
    "\n"
    "# ── SGD ──────────────────────────────────────────────────────────────────\n"
    "for gamma0 in [0.01, 0.05, 0.1, 0.5]:\n"
    "    for n_passes in [5, 10, 20]:\n"
    "        SOLVER_CONFIGS.append((SGDSolver, {'gamma0': gamma0, 'n_passes': n_passes},\n"
    "                               f'SGD(\u03b3={gamma0},T={n_passes})'))\n"
    "\n"
    "# ── ImplicitSGD ──────────────────────────────────────────────────────────\n"
    "for gamma0 in [0.01, 0.05, 0.1, 0.5]:\n"
    "    for n_passes in [5, 10, 20]:\n"
    "        SOLVER_CONFIGS.append((ImplicitSGDSolver, {'gamma0': gamma0, 'n_passes': n_passes},\n"
    "                               f'ISGD(\u03b3={gamma0},T={n_passes})'))\n"
    "\n"
    "# ── AdaGrad ──────────────────────────────────────────────────────────────\n"
    "for eta in [0.01, 0.05, 0.1, 0.5, 1.0]:\n"
    "    for n_passes in [5, 10, 20]:\n"
    "        SOLVER_CONFIGS.append((AdaGradSolver, {'eta': eta, 'n_passes': n_passes},\n"
    "                               f'AdaGrad(\u03b7={eta},T={n_passes})'))\n"
    "\n"
    "# ── FOBOS ────────────────────────────────────────────────────────────────\n"
    "for lam in [0.01, 0.05, 0.1]:\n"
    "    for gamma0 in [0.05, 0.1, 0.5]:\n"
    "        for n_passes in [5, 10]:\n"
    "            SOLVER_CONFIGS.append((FOBOSSolver,\n"
    "                                   {'lam': lam, 'gamma0': gamma0, 'n_passes': n_passes},\n"
    "                                   f'FOBOS(\u03bb={lam},\u03b3={gamma0},T={n_passes})'))\n"
    "\n"
    "# ── RDA ───────────────────────────────────────────────────────────────────\n"
    "for lam in [0.01, 0.05, 0.1]:\n"
    "    for gamma0 in [0.05, 0.1, 0.5]:\n"
    "        SOLVER_CONFIGS.append((RDASolver,\n"
    "                               {'lam': lam, 'gamma0': gamma0, 'n_passes': 5},\n"
    "                               f'RDA(\u03bb={lam},\u03b3={gamma0})'))\n"
    "\n"
    "# ── Truncated Gradient ────────────────────────────────────────────────────\n"
    "for lam in [0.01, 0.05, 0.1]:\n"
    "    for gamma0 in [0.05, 0.1, 0.5]:\n"
    "        for n_passes in [5, 10]:\n"
    "            SOLVER_CONFIGS.append((TruncatedGradientSolver,\n"
    "                                   {'lam': lam, 'gamma0': gamma0, 'n_passes': n_passes},\n"
    "                                   f'TruncGrad(\u03bb={lam},\u03b3={gamma0},T={n_passes})'))\n"
    "\n"
    "# ── RenewableGLM ──────────────────────────────────────────────────────────\n"
    "for n_batches in [5, 10, 20]:\n"
    "    SOLVER_CONFIGS.append((RenewableGLMSolver, {'n_batches': n_batches},\n"
    "                           f'Renewable(B={n_batches})'))\n"
    "\n"
    "print(f'Total solver configs: {len(SOLVER_CONFIGS)}')\n"
))

# ─────────────────────────────────────────────────────────────────────────────
# Section 3 – Run Arena
# ─────────────────────────────────────────────────────────────────────────────
cells.append(md_cell("## Section 3 – Run Arena (all datasets × all configs)"))

cells.append(code_cell(
    "FAMILY = {\n"
    "    OLSSolver:               'Classical',\n"
    "    GLMIRLSSolver:           'Classical',\n"
    "    LARSSolver:              'Classical',\n"
    "    RidgeSolver:             'Penalized',\n"
    "    LassoCDSolver:           'Penalized',\n"
    "    ElasticNetSolver:        'Penalized',\n"
    "    ISTASolver:              'First-order',\n"
    "    FISTASolver:             'First-order',\n"
    "    AdaptiveLassoSolver:     'Penalized',\n"
    "    SCADLLASolver:           'Penalized',\n"
    "    MCPCDSolver:             'Penalized',\n"
    "    GroupLassoSolver:        'Penalized',\n"
    "    FusedLassoSolver:        'Penalized',\n"
    "    SGDSolver:               'Online',\n"
    "    ImplicitSGDSolver:       'Online',\n"
    "    AdaGradSolver:           'Online',\n"
    "    FOBOSSolver:             'Online',\n"
    "    RDASolver:               'Online',\n"
    "    TruncatedGradientSolver: 'Online',\n"
    "    RenewableGLMSolver:      'Online',\n"
    "}\n"
    "\n"
    "FAMILY_COLORS = {\n"
    "    'Classical':   '#1f77b4',\n"
    "    'Penalized':   '#2ca02c',\n"
    "    'First-order': '#ff7f0e',\n"
    "    'Online':      '#d62728',\n"
    "}\n"
    "\n"
    "# Solvers restricted to regression (identity link)\n"
    "REGRESSION_ONLY = {LARSSolver, FusedLassoSolver}\n"
))

cells.append(code_cell(
    "results = []\n"
    "\n"
    "for ds_name, ds in datasets.items():\n"
    "    X, y, link, kind = ds['X'], ds['y'], ds['link'], ds['kind']\n"
    "    n, p = X.shape\n"
    "    print(f'\\n=== {ds_name} (n={n}, p={p}, {kind}) ===')\n"
    "    n_ok = 0\n"
    "\n"
    "    for SolverCls, cfg, label in SOLVER_CONFIGS:\n"
    "        # Skip regression-only solvers on logistic datasets\n"
    "        if kind == 'logistic' and SolverCls in REGRESSION_ONLY:\n"
    "            continue\n"
    "\n"
    "        # Build run config; inject groups for GroupLasso\n"
    "        run_cfg = dict(cfg)\n"
    "        if SolverCls is GroupLassoSolver:\n"
    "            n_groups = min(5, max(2, p // 5))\n"
    "            run_cfg['groups'] = [g.tolist() for g in np.array_split(np.arange(p), n_groups)]\n"
    "\n"
    "        try:\n"
    "            solver = SolverCls(**run_cfg)\n"
    "            result = solver.fit(X, y, link=link)\n"
    "            beta = result.beta_hat\n"
    "            if not np.all(np.isfinite(beta)):\n"
    "                raise ValueError('non-finite beta')\n"
    "            results.append({\n"
    "                'dataset':      ds_name,\n"
    "                'kind':         kind,\n"
    "                'solver_label': label,\n"
    "                'solver_class': SolverCls.__name__,\n"
    "                'family':       FAMILY[SolverCls],\n"
    "                'beta_hat':     beta.copy(),\n"
    "                'beta_norm':    float(np.linalg.norm(beta)),\n"
    "                'succeeded':    True,\n"
    "                'p':            p,\n"
    "            })\n"
    "            n_ok += 1\n"
    "        except Exception:\n"
    "            results.append({\n"
    "                'dataset':      ds_name,\n"
    "                'kind':         kind,\n"
    "                'solver_label': label,\n"
    "                'solver_class': SolverCls.__name__,\n"
    "                'family':       FAMILY.get(SolverCls, 'Unknown'),\n"
    "                'beta_hat':     None,\n"
    "                'beta_norm':    np.nan,\n"
    "                'succeeded':    False,\n"
    "                'p':            p,\n"
    "            })\n"
    "\n"
    "    print(f'  succeeded: {n_ok}')\n"
    "\n"
    "df = pd.DataFrame(results)\n"
    "print(f'\\nTotal runs:  {len(df)}')\n"
    "print(f'Succeeded:   {df[\"succeeded\"].sum()}')\n"
))

# ─────────────────────────────────────────────────────────────────────────────
# Section 4 – Summary
# ─────────────────────────────────────────────────────────────────────────────
cells.append(md_cell("## Section 4 – Results DataFrame + Success Summary"))

cells.append(code_cell(
    "summary = df.groupby(['dataset', 'succeeded']).size().unstack(fill_value=0)\n"
    "print(summary.to_string())\n"
))

cells.append(code_cell(
    "fam_ok = (df.groupby(['family', 'succeeded'])\n"
    "            .size()\n"
    "            .unstack(fill_value=0)\n"
    "            .rename(columns={True: 'succeeded', False: 'failed'}))\n"
    "fam_ok['success_%'] = 100 * fam_ok['succeeded'] / (fam_ok['succeeded'] + fam_ok.get('failed', 0))\n"
    "print(fam_ok.round(1).to_string())\n"
))

# ─────────────────────────────────────────────────────────────────────────────
# Section 5 – Outlier Filtering
# ─────────────────────────────────────────────────────────────────────────────
cells.append(md_cell("## Section 5 – Outlier Filtering"))

cells.append(code_cell(
    "def filter_outliers(df, thresh=5.0):\n"
    "    rows = []\n"
    "    for ds_name, grp in df[df['succeeded']].groupby('dataset'):\n"
    "        median_norm = grp['beta_norm'].median()\n"
    "        cutoff = thresh * (median_norm + 1e-12)\n"
    "        keep = grp['beta_norm'] <= cutoff\n"
    "        rows.append(grp[keep])\n"
    "        n_out = (~keep).sum()\n"
    "        if n_out > 0:\n"
    "            print(f'  {ds_name}: removed {n_out} outliers (cutoff={cutoff:.3f})')\n"
    "    return pd.concat(rows, ignore_index=True) if rows else pd.DataFrame()\n"
    "\n"
    "df_clean = filter_outliers(df, thresh=5.0)\n"
    "print(f'\\nClean runs: {len(df_clean)}')\n"
))

# ─────────────────────────────────────────────────────────────────────────────
# Section 6 – Per-Dataset t-SNE + UMAP
# ─────────────────────────────────────────────────────────────────────────────
cells.append(md_cell(
    "## Section 6 – Per-Dataset t-SNE + UMAP Embeddings\n\n"
    "One figure per dataset. Each point = one (solver, hyperparams) run. "
    "Color = solver family."
))

cells.append(code_cell(
    "embed_results = {}  # cache for combined MDS\n"
    "\n"
    "for ds_name, grp in df_clean.groupby('dataset'):\n"
    "    n_pts = len(grp)\n"
    "    if n_pts < 5:\n"
    "        print(f'Skipping {ds_name}: only {n_pts} clean runs')\n"
    "        continue\n"
    "\n"
    "    betas    = np.vstack(grp['beta_hat'].values)\n"
    "    p        = betas.shape[1]\n"
    "    families = grp['family'].values\n"
    "\n"
    "    # t-SNE\n"
    "    perplexity = min(30, max(5, n_pts // 5))\n"
    "    tsne_coords = TSNE(\n"
    "        n_components=2, perplexity=perplexity, random_state=42,\n"
    "        max_iter=1000, init='pca'\n"
    "    ).fit_transform(betas)\n"
    "\n"
    "    # UMAP\n"
    "    n_neighbors = min(15, max(3, n_pts // 5))\n"
    "    umap_coords = umap.UMAP(\n"
    "        n_components=2, n_neighbors=n_neighbors,\n"
    "        random_state=42, min_dist=0.1\n"
    "    ).fit_transform(betas)\n"
    "\n"
    "    embed_results[ds_name] = {\n"
    "        'tsne': tsne_coords, 'umap': umap_coords,\n"
    "        'families': families, 'p': p,\n"
    "    }\n"
    "\n"
    "    # ── Plot ────────────────────────────────────────────────────────────────\n"
    "    fig, axes = plt.subplots(1, 2, figsize=(18, 7))\n"
    "    fig.suptitle(f'{ds_name}  (n_configs={n_pts}, p={p})',\n"
    "                 fontsize=14, fontweight='bold')\n"
    "\n"
    "    for ax, coords, method in zip(axes,\n"
    "                                   [tsne_coords, umap_coords],\n"
    "                                   ['t-SNE', 'UMAP']):\n"
    "        for fam in np.unique(families):\n"
    "            mask = families == fam\n"
    "            ax.scatter(\n"
    "                coords[mask, 0], coords[mask, 1],\n"
    "                c=FAMILY_COLORS.get(fam, 'gray'),\n"
    "                label=fam, alpha=0.7, s=45, edgecolors='none'\n"
    "            )\n"
    "        # Centroid annotations\n"
    "        for fam in np.unique(families):\n"
    "            mask = families == fam\n"
    "            cx, cy = coords[mask, 0].mean(), coords[mask, 1].mean()\n"
    "            ax.annotate(\n"
    "                fam, (cx, cy), fontsize=7, ha='center', fontweight='bold',\n"
    "                color=FAMILY_COLORS.get(fam, 'gray'),\n"
    "                bbox=dict(boxstyle='round,pad=0.2', facecolor='white',\n"
    "                          alpha=0.6, edgecolor='none')\n"
    "            )\n"
    "        ax.set_title(method, fontsize=12)\n"
    "        ax.set_xlabel(f'{method}1'); ax.set_ylabel(f'{method}2')\n"
    "        ax.tick_params(left=False, bottom=False, labelleft=False, labelbottom=False)\n"
    "        for spine in ax.spines.values():\n"
    "            spine.set_visible(False)\n"
    "\n"
    "    handles = [mpatches.Patch(color=FAMILY_COLORS[f], label=f)\n"
    "               for f in FAMILY_COLORS if f in grp['family'].values]\n"
    "    axes[1].legend(handles=handles, loc='best', framealpha=0.8, fontsize=9)\n"
    "\n"
    "    plt.tight_layout()\n"
    "    safe = ds_name.replace(' ', '_').replace('/', '_')\n"
    "    fig.savefig(f'fig_embed_{safe}.png', dpi=100, bbox_inches='tight')\n"
    "    plt.show()\n"
    "    print(f'  Saved fig_embed_{safe}.png')\n"
))

# ─────────────────────────────────────────────────────────────────────────────
# Section 7 – Additional Visualizations
# ─────────────────────────────────────────────────────────────────────────────
cells.append(md_cell("## Section 7 – Additional Visualizations"))

cells.append(code_cell(
    "# ── Norm boxplot by solver family ─────────────────────────────────────────\n"
    "fam_order = ['Classical', 'Penalized', 'First-order', 'Online']\n"
    "fams_present = [f for f in fam_order if f in df_clean['family'].values]\n"
    "data_by_fam = [df_clean.loc[df_clean['family'] == f, 'beta_norm'].dropna().values\n"
    "               for f in fams_present]\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(10, 6))\n"
    "bp = ax.boxplot(data_by_fam, labels=fams_present, patch_artist=True,\n"
    "                medianprops=dict(color='black', lw=2))\n"
    "for patch, fam in zip(bp['boxes'], fams_present):\n"
    "    patch.set_facecolor(FAMILY_COLORS[fam])\n"
    "    patch.set_alpha(0.7)\n"
    "ax.set_ylabel(r'$\\|\\hat{\\beta}\\|_2$', fontsize=13)\n"
    "ax.set_title('Distribution of Solution Norms by Solver Family', fontsize=13)\n"
    "ax.yaxis.grid(True, alpha=0.3)\n"
    "plt.tight_layout()\n"
    "plt.savefig('fig_norm_boxplot.png', dpi=100, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved fig_norm_boxplot.png')\n"
))

cells.append(code_cell(
    "# ── Combined MDS: mean beta per (dataset, family) ─────────────────────────\n"
    "rows_mds = []\n"
    "for ds_name, grp in df_clean.groupby('dataset'):\n"
    "    for fam, fg in grp.groupby('family'):\n"
    "        mean_b = np.vstack(fg['beta_hat'].values).mean(axis=0)\n"
    "        rows_mds.append({'dataset': ds_name, 'family': fam, 'mean_beta': mean_b})\n"
    "\n"
    "if rows_mds:\n"
    "    df_mds = pd.DataFrame(rows_mds)\n"
    "    max_p  = max(b.shape[0] for b in df_mds['mean_beta'])\n"
    "    mat    = np.vstack([\n"
    "        np.concatenate([b, np.zeros(max_p - len(b))]) for b in df_mds['mean_beta']\n"
    "    ])\n"
    "    mds_coords = MDS(n_components=2, random_state=42,\n"
    "                     dissimilarity='euclidean',\n"
    "                     normalized_stress='auto').fit_transform(mat)\n"
    "\n"
    "    ds_list   = df_mds['dataset'].unique()\n"
    "    ds_cmap   = dict(zip(ds_list, plt.cm.tab20(np.linspace(0, 1, len(ds_list)))))\n"
    "    fam_mark  = {'Classical': 'o', 'Penalized': 's', 'First-order': '^', 'Online': 'D'}\n"
    "\n"
    "    fig, ax = plt.subplots(figsize=(14, 10))\n"
    "    for i, row in df_mds.iterrows():\n"
    "        ax.scatter(mds_coords[i, 0], mds_coords[i, 1],\n"
    "                   color=ds_cmap[row['dataset']],\n"
    "                   marker=fam_mark.get(row['family'], 'o'),\n"
    "                   s=80, alpha=0.8, edgecolors='white', linewidths=0.5)\n"
    "\n"
    "    ds_handles = [mpatches.Patch(color=ds_cmap[d], label=d) for d in ds_list]\n"
    "    leg1 = ax.legend(handles=ds_handles, loc='upper left', fontsize=7,\n"
    "                     title='Dataset', ncol=2, framealpha=0.8)\n"
    "    ax.add_artist(leg1)\n"
    "\n"
    "    fam_handles = [Line2D([0], [0], marker=fam_mark.get(f, 'o'), color='gray',\n"
    "                          markersize=8, linestyle='None', label=f)\n"
    "                   for f in fam_mark if f in df_mds['family'].values]\n"
    "    ax.legend(handles=fam_handles, loc='lower right', fontsize=9,\n"
    "              title='Solver Family', framealpha=0.8)\n"
    "\n"
    "    ax.set_title('Combined MDS: Mean Beta per (Dataset, Family)', fontsize=13)\n"
    "    ax.set_xlabel('MDS1'); ax.set_ylabel('MDS2')\n"
    "    for spine in ax.spines.values():\n"
    "        spine.set_visible(False)\n"
    "    ax.tick_params(left=False, bottom=False, labelleft=False, labelbottom=False)\n"
    "    plt.tight_layout()\n"
    "    plt.savefig('fig_combined_mds.png', dpi=100, bbox_inches='tight')\n"
    "    plt.show()\n"
    "    print('Saved fig_combined_mds.png')\n"
))

cells.append(code_cell(
    "# ── Success-rate heatmap ──────────────────────────────────────────────────\n"
    "pivot = (df.groupby(['dataset', 'family'])['succeeded']\n"
    "           .mean().unstack(fill_value=np.nan) * 100)\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(10, max(6, len(pivot) * 0.5)))\n"
    "im = ax.imshow(pivot.values, aspect='auto', cmap='RdYlGn', vmin=0, vmax=100)\n"
    "ax.set_xticks(range(len(pivot.columns)))\n"
    "ax.set_xticklabels(pivot.columns, rotation=30, ha='right', fontsize=10)\n"
    "ax.set_yticks(range(len(pivot.index)))\n"
    "ax.set_yticklabels(pivot.index, fontsize=9)\n"
    "plt.colorbar(im, ax=ax, label='Success Rate (%)')\n"
    "ax.set_title('Solver Family Success Rate per Dataset (%)', fontsize=12)\n"
    "for i in range(pivot.shape[0]):\n"
    "    for j in range(pivot.shape[1]):\n"
    "        v = pivot.values[i, j]\n"
    "        if not np.isnan(v):\n"
    "            ax.text(j, i, f'{v:.0f}', ha='center', va='center', fontsize=8,\n"
    "                    color='black' if 20 < v < 80 else 'white')\n"
    "plt.tight_layout()\n"
    "plt.savefig('fig_success_heatmap.png', dpi=100, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved fig_success_heatmap.png')\n"
))

# ─────────────────────────────────────────────────────────────────────────────
# Section 8 – Key Observations
# ─────────────────────────────────────────────────────────────────────────────
cells.append(md_cell(
    "## Section 8 – Key Observations\n\n"
    "- **Classical solvers** (OLS, IRLS, LARS) produce unique, data-driven solutions "
    "and form tight isolated clusters in the embedding — no regularisation manifold.\n"
    "- **Penalized solvers** (Ridge, Lasso, ElasticNet, SCAD, MCP, AdaLasso, "
    "GroupLasso, FusedLasso) spread along a regularisation manifold controlled by λ. "
    "Small-λ configs approach OLS; large-λ configs shrink toward zero.\n"
    "- **First-order solvers** (ISTA, FISTA) follow a manifold similar to Lasso CD "
    "but with slightly different convergence geometry.\n"
    "- **Online solvers** (SGD, ISGD, AdaGrad, FOBOS, RDA, TruncGrad, Renewable) "
    "form a diffuse cloud due to stochastic noise in the optimisation trajectory; "
    "more passes (T) and smaller step sizes bring them closer to the batch solution.\n"
    "- **t-SNE** reveals tight local sub-clusters within each family.\n"
    "- **UMAP** better preserves the global regularisation continuum, showing the "
    "smooth transition from unpenalised to heavily shrunk solutions.\n"
    "- The relative geometry of solver families is **consistent across datasets**, "
    "suggesting the topology reflects algorithmic properties more than data geometry.\n"
))

# ─────────────────────────────────────────────────────────────────────────────
# Write notebook
# ─────────────────────────────────────────────────────────────────────────────
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python", "version": "3.11.0"},
    },
    "cells": cells,
}

out = os.path.join(ROOT, "notebooks", "phase2_multidata.ipynb")
with open(out, "w", encoding="utf-8") as fh:
    json.dump(nb, fh, ensure_ascii=False, indent=1)

print(f"Notebook written to {out}")
print(f"Total cells: {len(cells)}")
